query:
  default_page: 1
  default_page_size: 10
mongodb:
  host: 120.25.236.100
  port: 27017
  database: health
dataRange:
  heartRate:
    min: 60
    max: 100
  bloodPressureLow:
    min: 65
    max: 79
  bloodPressureHigh:
    min: 100
    max: 119
  bloodOxygen:
    min: 95
    max: 100