FROM ubuntu:20.04
RUN apt update && apt install openssl
COPY health-monitoring-server-static .
RUN chmod +x health-monitoring-server-static
COPY config.yaml .
COPY static ./static
ENV SERVER_PORT=9998
EXPOSE ${SERVER_PORT}
CMD [ "./health-monitoring-server-static" ]