server:
  url: http://120.25.236.100:9999/data
interval: 1800000
data:
  - dataType: heartRate
    min: 55
    max: 70
  - dataType: bloodPressureLow
    min: 65
    max: 79
  - dataType: bloodPressureHigh
    min: 100
    max: 119
  - dataType: bloodOxygen
    min: 95
    max: 100
  - dataType: floorClimbed
    min: 0
    max: 1
    beginTime: 7
    endTime: 22
  - dataType: stepCount
    min: 300
    max: 500
    beginTime: 8
    endTime: 21
  - dataType: walkingDistance
    min: 400
    max: 550
    beginTime: 8
    endTime: 21
  - dataType: runningDistance
    min: 0
    max: 2000
    beginTime: 19
    endTime: 21