name: Client Deploy

on:
    push:
        branches: [ master ]
        paths:
            - "client/**"
    workflow_dispatch:

jobs:
    build:
        name: build
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2
            - name: setup node
              uses: actions/setup-node@v2
              with:
                node-version: "16.16.0"
            - run: cd client && yarn install
              name: install dependencies
            - run: cd client && yarn build
              name: build
            - name: tar dist directory
              run: cd client && tar -czvf dist.tar.gz dist
            - name: upload to server
              uses: garygrossgarten/github-action-scp@release
              with:
                local: client/dist.tar.gz
                remote: health-monitoring/dist.tar.gz
                host: ${{ secrets.HOST }}
                username: ${{ secrets.SSH_USER }}
                password: ${{ secrets.SSH_PASSWORD }}
            - name: untar and run
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.HOST }}
                username: ${{ secrets.SSH_USER }}
                password: ${{ secrets.SSH_PASSWORD }}
                script: |
                    cd health-monitoring
                    rm -r ./static
                    tar -xzvf dist.tar.gz
                    mv dist static